### ISSUE TITLE
Cannot launch gdb

### ISSUE THREAD

**Issue by atauzki** [jmeubank/tdm-binutils-gdb#1]
gdb version: 10.2.0-tdm64-1 (installed from the latest installer)
open command prompt and input `gdb`
then it exits with error "missing libreadline8.dll"

**Comment by jmeubank** [comment]
Sorry, looks like a packaging error! I've added https://github.com/jmeubank/tdm-binutils-gdb/releases/tag/v10.2-tdm64-2 to address this, the installer will be updated in a little while.

**Comment by atauzki** [comment]
OK. It works fine. Thanks.

**Comment by jmeubank** [comment]
New versions of the tdm-gcc-webdl.exe and tdm64-gcc-10.3.0-2.exe installers are now uploaded as well.
